version: '3.8'

services:
  homepage:
    build:
      context: .
      dockerfile: dockerfile
    container_name: homepage-app
    ports:
      - "7400:80"
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
